# Generated by Django 2.2.13 on 2020-06-14 10:52

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('learning_spaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='spaceLeftoverRequest',
            fields=[
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=400)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete='', to=settings.AUTH_USER_MODEL)),
                ('targetUser', models.ForeignKey(blank=True, null=True, on_delete='', related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
