# Generated by Django 2.2.12 on 2020-05-24 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_spaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='id',
            new_name='identifier',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='id',
            new_name='identifier',
        ),
    ]
