# Generated by Django 2.2.13 on 2020-06-14 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_spaces', '0002_spaceleftoverrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceleftoverrequest',
            name='reservation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_spaces.Reservation'),
        ),
    ]
