# Generated by Django 2.2.13 on 2020-06-14 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_spaces', '0003_spaceleftoverrequest_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceleftoverrequest',
            name='reservation',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='learning_spaces.Reservation'),
            preserve_default=False,
        ),
    ]
