# Generated by Django 2.2.1 on 2020-08-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_spaces', '0006_room_ressources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='ressources',
            field=models.BooleanField(choices=[('BE', 'Beamer'), ('WB', 'Whiteboard'), ('BO', 'Normale Tafel')], default=None, max_length=2),
        ),
    ]
