# Generated by Django 2.2.1 on 2020-08-31 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_spaces', '0008_auto_20200831_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='ressources',
        ),
    ]
